extern int is_punc(char c);
extern int adjacent_check(char* letter, int letter_length, int idx);
extern int punc_and_cap(char* letter, int letter_length);
extern int is_trigram(char* str);
extern int get_next_word_idx(char* letter, int letter_length, int current_idx);
extern int trigram_check(char* letter, int letter_length);
extern int start_capital_check(char* letter, int letter_length);
extern int repeating_char_check(char*letter, int letter_length);
extern int space_ratio_check(char* letter, int letter_length);
extern int has_punctuation(char* letter, int letter_length);
extern int runon_check(char* letter, int letter_length);
extern int chunk_check(char* letter, int letter_length);
extern int score_letter(char* letter, int letter_length);
