#include <stdio.h>

#include "ascii.h"
#include "trigram_table.h"

static int a_table[] = {
  CHAR_b, CHAR_l,
  CHAR_b, CHAR_o,
  CHAR_b, CHAR_r,
  CHAR_b, CHAR_s,
  CHAR_c, CHAR_c,
  CHAR_c, CHAR_h,
  CHAR_c, CHAR_r,
  CHAR_c, CHAR_t,
  CHAR_d, CHAR_d,
  CHAR_d, CHAR_m,
  CHAR_d, CHAR_v,
  CHAR_e, CHAR_r,
  CHAR_f, CHAR_f,
  CHAR_f, CHAR_r,
  CHAR_f, CHAR_t,
  CHAR_g, CHAR_a,
  CHAR_g, CHAR_e,
  CHAR_g, CHAR_o,
  CHAR_h, CHAR_e,
  CHAR_i, CHAR_r,
  CHAR_l, CHAR_i,
  CHAR_l, CHAR_l,
  CHAR_l, CHAR_m,
  CHAR_l, CHAR_o,
  CHAR_l, CHAR_r,
  CHAR_l, CHAR_s,
  CHAR_l, CHAR_t,
  CHAR_l, CHAR_w,
  CHAR_m, CHAR_SPACE,
  CHAR_m, CHAR_e,
  CHAR_m, CHAR_o,
  CHAR_n, CHAR_d,
  CHAR_n, CHAR_g,
  CHAR_n, CHAR_i,
  CHAR_n, CHAR_o,
  CHAR_n, CHAR_s,
  CHAR_n, CHAR_y,
  CHAR_p, CHAR_a,
  CHAR_p, CHAR_p,
  CHAR_p, CHAR_r,
  CHAR_r, CHAR_e,
  CHAR_r, CHAR_g,
  CHAR_r, CHAR_m,
  CHAR_r, CHAR_r,
  CHAR_r, CHAR_t,
  CHAR_s, CHAR_i,
  CHAR_s, CHAR_k,
  CHAR_s, CHAR_l,
  CHAR_t, CHAR_e,
  CHAR_t, CHAR_m,
  CHAR_t, CHAR_t,
  CHAR_u, CHAR_d,
  CHAR_u, CHAR_g,
  CHAR_u, CHAR_t,
  CHAR_v, CHAR_e,
  CHAR_v, CHAR_o,
  CHAR_w, CHAR_a,

};

static int b_table[] = {
  CHAR_a, CHAR_b,
  CHAR_a, CHAR_c,
  CHAR_a, CHAR_d,
  CHAR_a, CHAR_g,
  CHAR_a, CHAR_l,
  CHAR_a, CHAR_n,
  CHAR_a, CHAR_s,
  CHAR_a, CHAR_t,
  CHAR_e, CHAR_SPACE,
  CHAR_e, CHAR_a,
  CHAR_e, CHAR_c,
  CHAR_e, CHAR_d,
  CHAR_e, CHAR_e,
  CHAR_e, CHAR_f,
  CHAR_e, CHAR_g,
  CHAR_e, CHAR_h,
  CHAR_e, CHAR_l,
  CHAR_e, CHAR_s,
  CHAR_e, CHAR_t,
  CHAR_e, CHAR_y,
  CHAR_i, CHAR_c,
  CHAR_i, CHAR_g,
  CHAR_i, CHAR_k,
  CHAR_i, CHAR_l,
  CHAR_i, CHAR_r,
  CHAR_i, CHAR_t,
  CHAR_l, CHAR_a,
  CHAR_l, CHAR_e,
  CHAR_l, CHAR_o,
  CHAR_l, CHAR_u,
  CHAR_o, CHAR_a,
  CHAR_o, CHAR_d,
  CHAR_o, CHAR_n,
  CHAR_o, CHAR_o,
  CHAR_o, CHAR_r,
  CHAR_o, CHAR_t,
  CHAR_o, CHAR_u,
  CHAR_o, CHAR_x,
  CHAR_o, CHAR_y,
  CHAR_r, CHAR_a,
  CHAR_r, CHAR_e,
  CHAR_r, CHAR_i,
  CHAR_r, CHAR_o,
  CHAR_u, CHAR_i,
  CHAR_u, CHAR_r,
  CHAR_u, CHAR_s,
  CHAR_u, CHAR_t,
  CHAR_u, CHAR_y,
  CHAR_y, CHAR_SPACE,
};

static int c_table[] = {
  CHAR_a, CHAR_k,
  CHAR_a, CHAR_l,
  CHAR_a, CHAR_m,
  CHAR_a, CHAR_n,
  CHAR_a, CHAR_p,
  CHAR_a, CHAR_r,
  CHAR_a, CHAR_s,
  CHAR_a, CHAR_t,
  CHAR_a, CHAR_u,
  CHAR_e, CHAR_n,
  CHAR_e, CHAR_r,
  CHAR_h, CHAR_a,
  CHAR_h, CHAR_e,
  CHAR_h, CHAR_i,
  CHAR_h, CHAR_o,
  CHAR_h, CHAR_i,
  CHAR_h, CHAR_u,
  CHAR_i, CHAR_r,
  CHAR_i, CHAR_t,
  CHAR_l, CHAR_a,
  CHAR_l, CHAR_e,
  CHAR_l, CHAR_i,
  CHAR_l, CHAR_o,
  CHAR_o, CHAR_a,
  CHAR_o, CHAR_f,
  CHAR_o, CHAR_i,
  CHAR_o, CHAR_l,
  CHAR_o, CHAR_m,
  CHAR_o, CHAR_n,
  CHAR_o, CHAR_o,
  CHAR_o, CHAR_p,
  CHAR_o, CHAR_r,
  CHAR_o, CHAR_s,
  CHAR_o, CHAR_u,
  CHAR_o, CHAR_v,
  CHAR_o, CHAR_w,
  CHAR_r, CHAR_e,
  CHAR_r, CHAR_i,
  CHAR_r, CHAR_o,
  CHAR_r, CHAR_y,
  CHAR_u, CHAR_p,
  CHAR_u, CHAR_r,
  CHAR_u, CHAR_s,
  CHAR_u, CHAR_t,
};

static int d_table[] = {
  CHAR_a, CHAR_d,
  CHAR_a, CHAR_i,
  CHAR_a, CHAR_m,
  CHAR_a, CHAR_n,
  CHAR_a, CHAR_r,
  CHAR_a, CHAR_t,
  CHAR_a, CHAR_u,
  CHAR_a, CHAR_y,
  CHAR_e, CHAR_a,
  CHAR_e, CHAR_c,
  CHAR_e, CHAR_e,
  CHAR_e, CHAR_f,
  CHAR_e, CHAR_g,
  CHAR_e, CHAR_l,
  CHAR_e, CHAR_m,
  CHAR_e, CHAR_n,
  CHAR_e, CHAR_p,
  CHAR_e, CHAR_s,
  CHAR_e, CHAR_t,
  CHAR_e, CHAR_v,
  CHAR_i, CHAR_c,
  CHAR_i, CHAR_d,
  CHAR_i, CHAR_e,
  CHAR_i, CHAR_f,
  CHAR_i, CHAR_g,
  CHAR_i, CHAR_n,
  CHAR_i, CHAR_r,
  CHAR_i, CHAR_s,
  CHAR_i, CHAR_v,
  CHAR_o, CHAR_SPACE,
  CHAR_o, CHAR_c,
  CHAR_o, CHAR_e,
  CHAR_o, CHAR_g,
  CHAR_o, CHAR_l,
  CHAR_o, CHAR_n,
  CHAR_o, CHAR_o,
  CHAR_o, CHAR_u,
  CHAR_o, CHAR_w,
  CHAR_o, CHAR_z,
  CHAR_r, CHAR_a,
  CHAR_r, CHAR_e,
  CHAR_r, CHAR_i,
  CHAR_r, CHAR_o,
  CHAR_r, CHAR_u,
  CHAR_r, CHAR_y,
  CHAR_u, CHAR_e,
  CHAR_u, CHAR_r,
  CHAR_u, CHAR_s,
  CHAR_u, CHAR_t,
};

static int e_table[] = {
    CHAR_a, CHAR_c,
    CHAR_a, CHAR_r,
    CHAR_a, CHAR_s,
    CHAR_a, CHAR_t,
    CHAR_d, CHAR_u,
    CHAR_f, CHAR_f,
    CHAR_g, CHAR_g,
    CHAR_i, CHAR_g,
    CHAR_i, CHAR_t,
    CHAR_l, CHAR_e,
    CHAR_l, CHAR_s,
    CHAR_m, CHAR_p,
    CHAR_n, CHAR_d,
    CHAR_n, CHAR_e,
    CHAR_n, CHAR_g,
    CHAR_n, CHAR_j,
    CHAR_n, CHAR_o,
    CHAR_n, CHAR_t,
    CHAR_q, CHAR_u,
    CHAR_r, CHAR_r,
    CHAR_s, CHAR_p,
    CHAR_u, CHAR_r,
    CHAR_v, CHAR_e,
    CHAR_x, CHAR_a,
    CHAR_x, CHAR_c,
    CHAR_x, CHAR_e,
    CHAR_x, CHAR_p,
    CHAR_y, CHAR_e,
};

static int f_table[] = {
    CHAR_a, CHAR_c,
    CHAR_a, CHAR_i,
    CHAR_a, CHAR_l,
    CHAR_a, CHAR_m,
    CHAR_a, CHAR_r,
    CHAR_a, CHAR_s,
    CHAR_a, CHAR_t,
    CHAR_e, CHAR_a,
    CHAR_e, CHAR_b,
    CHAR_e, CHAR_d,
    CHAR_e, CHAR_e,
    CHAR_e, CHAR_l,
    CHAR_e, CHAR_w,
    CHAR_i, CHAR_e,
    CHAR_i, CHAR_f,
    CHAR_i, CHAR_g,
    CHAR_i, CHAR_l,
    CHAR_i, CHAR_n,
    CHAR_i, CHAR_r,
    CHAR_i, CHAR_s,
    CHAR_i, CHAR_v,
    CHAR_i, CHAR_x,
    CHAR_l, CHAR_a,
    CHAR_l, CHAR_e,
    CHAR_l, CHAR_i,
    CHAR_l, CHAR_o,
    CHAR_l, CHAR_y,
    CHAR_o, CHAR_l,
    CHAR_o, CHAR_o,
    CHAR_o, CHAR_r,
    CHAR_o, CHAR_u,
    CHAR_r, CHAR_a,
    CHAR_r, CHAR_e,
    CHAR_r, CHAR_i,
    CHAR_r, CHAR_o,
    CHAR_r, CHAR_u,
    CHAR_u, CHAR_l,
    CHAR_u, CHAR_n,
    CHAR_u, CHAR_t,
};

static int g_table[] = {
    CHAR_a, CHAR_i,
    CHAR_a, CHAR_m,
    CHAR_a, CHAR_r,
    CHAR_a, CHAR_s,
    CHAR_a, CHAR_t,
    CHAR_a, CHAR_v,
    CHAR_e, CHAR_n,
    CHAR_e, CHAR_r,
    CHAR_e, CHAR_t,
    CHAR_i, CHAR_r,
    CHAR_i, CHAR_v,
    CHAR_l, CHAR_a,
    CHAR_o, CHAR_SPACE,
    CHAR_o, CHAR_d,
    CHAR_o, CHAR_i,
    CHAR_o, CHAR_n,
    CHAR_o, CHAR_o,
    CHAR_o, CHAR_t,
    CHAR_o, CHAR_v,
    CHAR_r, CHAR_a,
    CHAR_r, CHAR_e,
    CHAR_r, CHAR_o,
    CHAR_u, CHAR_a,
    CHAR_u, CHAR_e,
    CHAR_u, CHAR_i,
    CHAR_u, CHAR_n,
};

static int h_table[] = {
    CHAR_a, CHAR_b,
    CHAR_a, CHAR_d,
    CHAR_a, CHAR_i,
    CHAR_a, CHAR_l,
    CHAR_a, CHAR_n,
    CHAR_a, CHAR_p,
    CHAR_a, CHAR_r,
    CHAR_a, CHAR_s,
    CHAR_a, CHAR_t,
    CHAR_a, CHAR_v,
    CHAR_e, CHAR_SPACE,
    CHAR_e, CHAR_a,
    CHAR_e, CHAR_i,
    CHAR_e, CHAR_l,
    CHAR_e, CHAR_r,
    CHAR_i, CHAR_SPACE,
    CHAR_i, CHAR_d,
    CHAR_i, CHAR_g,
    CHAR_i, CHAR_l,
    CHAR_i, CHAR_m,
    CHAR_i, CHAR_r,
    CHAR_i, CHAR_s,
    CHAR_i, CHAR_t,
    CHAR_o, CHAR_l,
    CHAR_o, CHAR_m,
    CHAR_o, CHAR_n,
    CHAR_o, CHAR_p,
    CHAR_o, CHAR_r,
    CHAR_o, CHAR_s,
    CHAR_o, CHAR_t,
    CHAR_o, CHAR_u,
    CHAR_o, CHAR_w,
    CHAR_u, CHAR_m,
    CHAR_u, CHAR_n,
    CHAR_u, CHAR_r,
    CHAR_u, CHAR_s,
};

static int i_table[] = {
    CHAR_SPACE, CHAR_SPACE,
    CHAR_c, CHAR_e,
    CHAR_d, CHAR_e,
    CHAR_f, CHAR_SPACE,
    CHAR_m, CHAR_a,
    CHAR_m, CHAR_m,
    CHAR_m, CHAR_p,
    CHAR_n, CHAR_SPACE,
    CHAR_n, CHAR_c,
    CHAR_n, CHAR_d,
    CHAR_n, CHAR_f,
    CHAR_n, CHAR_s,
    CHAR_n, CHAR_t,
    CHAR_n, CHAR_v,
    CHAR_r, CHAR_o,
    CHAR_s, CHAR_SPACE,
    CHAR_s, CHAR_l,
    CHAR_t, CHAR_SPACE,
    CHAR_t, CHAR_s,
};

static int j_table[] = {
    CHAR_a, CHAR_n,
    CHAR_a, CHAR_p,
    CHAR_o, CHAR_b,
    CHAR_o, CHAR_i,
    CHAR_u, CHAR_d,
    CHAR_u, CHAR_l,
    CHAR_u, CHAR_m,
    CHAR_u, CHAR_n,
    CHAR_u, CHAR_s,
};

static int k_table[] = {
    CHAR_e, CHAR_e,
    CHAR_e, CHAR_p,
    CHAR_e, CHAR_y,
    CHAR_i, CHAR_c,
    CHAR_i, CHAR_l,
    CHAR_i, CHAR_n,
    CHAR_i, CHAR_t,
    CHAR_n, CHAR_e,
    CHAR_n, CHAR_i,
    CHAR_n, CHAR_o,
};

static int l_table[] = {
    CHAR_a, CHAR_b,
    CHAR_a, CHAR_d,
    CHAR_a, CHAR_i,
    CHAR_a, CHAR_k,
    CHAR_a, CHAR_n,
    CHAR_a, CHAR_r,
    CHAR_a, CHAR_s,
    CHAR_a, CHAR_t,
    CHAR_a, CHAR_u,
    CHAR_a, CHAR_w,
    CHAR_a, CHAR_y,
    CHAR_a, CHAR_z,
    CHAR_e, CHAR_a,
    CHAR_e, CHAR_d,
    CHAR_e, CHAR_f,
    CHAR_e, CHAR_g,
    CHAR_e, CHAR_n,
    CHAR_e, CHAR_s,
    CHAR_e, CHAR_t,
    CHAR_e, CHAR_v,
    CHAR_i, CHAR_b,
    CHAR_i, CHAR_e,
    CHAR_i, CHAR_f,
    CHAR_i, CHAR_g,
    CHAR_i, CHAR_k,
    CHAR_i, CHAR_m,
    CHAR_i, CHAR_n,
    CHAR_i, CHAR_s,
    CHAR_i, CHAR_t,
    CHAR_i, CHAR_v,
    CHAR_o, CHAR_c,
    CHAR_o, CHAR_n,
    CHAR_o, CHAR_o,
    CHAR_o, CHAR_s,
    CHAR_o, CHAR_t,
    CHAR_o, CHAR_u,
    CHAR_o, CHAR_v,
    CHAR_o, CHAR_w,
    CHAR_u, CHAR_n,
    CHAR_y, CHAR_i,
};

static int m_table[] = {
    CHAR_a, CHAR_c,
    CHAR_a, CHAR_d,
    CHAR_a, CHAR_g,
    CHAR_a, CHAR_i,
    CHAR_a, CHAR_j,
    CHAR_a, CHAR_k,
    CHAR_a, CHAR_n,
    CHAR_a, CHAR_p,
    CHAR_a, CHAR_r,
    CHAR_a, CHAR_t,
    CHAR_a, CHAR_y,
    CHAR_e, CHAR_SPACE,
    CHAR_e, CHAR_a,
    CHAR_e, CHAR_d,
    CHAR_e, CHAR_e,
    CHAR_e, CHAR_m,
    CHAR_e, CHAR_n,
    CHAR_e, CHAR_s,
    CHAR_e, CHAR_t,
    CHAR_i, CHAR_d,
    CHAR_i, CHAR_g,
    CHAR_i, CHAR_l,
    CHAR_i, CHAR_n,
    CHAR_i, CHAR_s,
    CHAR_o, CHAR_d,
    CHAR_o, CHAR_m,
    CHAR_o, CHAR_n,
    CHAR_o, CHAR_o,
    CHAR_o, CHAR_r,
    CHAR_o, CHAR_s,
    CHAR_o, CHAR_t,
    CHAR_o, CHAR_u,
    CHAR_o, CHAR_v,
    CHAR_u, CHAR_c,
    CHAR_u, CHAR_m,
    CHAR_u, CHAR_s,
    CHAR_y, CHAR_SPACE,
    CHAR_y, CHAR_s,
};

static int n_table[] = {
    CHAR_a, CHAR_m,
    CHAR_a, CHAR_r,
    CHAR_a, CHAR_t,
    CHAR_e, CHAR_a,
    CHAR_e, CHAR_c,
    CHAR_e, CHAR_e,
    CHAR_e, CHAR_i,
    CHAR_e, CHAR_v,
    CHAR_e, CHAR_w,
    CHAR_e, CHAR_x,
    CHAR_i, CHAR_c,
    CHAR_i, CHAR_g,
    CHAR_i, CHAR_n,
    CHAR_o, CHAR_SPACE,
    CHAR_o, CHAR_b,
    CHAR_o, CHAR_i,
    CHAR_o, CHAR_n,
    CHAR_o, CHAR_o,
    CHAR_o, CHAR_r,
    CHAR_o, CHAR_s,
    CHAR_o, CHAR_t,
    CHAR_o, CHAR_v,
    CHAR_o, CHAR_w,
    CHAR_u, CHAR_m,
};

static int o_table[] = {
    CHAR_b, CHAR_j,
    CHAR_APOSTROPHE, CHAR_c,
    CHAR_c, CHAR_t,
    CHAR_f, CHAR_SPACE,
    CHAR_f, CHAR_f,
    CHAR_f, CHAR_t,
    CHAR_h, CHAR_SPACE,
    CHAR_i, CHAR_l,
    CHAR_k, CHAR_a,
    CHAR_l, CHAR_d,
    CHAR_n, CHAR_SPACE,
    CHAR_n, CHAR_c,
    CHAR_n, CHAR_e,
    CHAR_n, CHAR_l,
    CHAR_p, CHAR_e,
    CHAR_p, CHAR_i,
    CHAR_p, CHAR_p,
    CHAR_r, CHAR_SPACE,
    CHAR_r, CHAR_a,
    CHAR_r, CHAR_d,
    CHAR_t, CHAR_h,
    CHAR_u, CHAR_r,
    CHAR_u, CHAR_t,
    CHAR_v, CHAR_e,
    CHAR_w, CHAR_n,
};

static int p_table[] = {
    CHAR_a, CHAR_c,
    CHAR_a, CHAR_g,
    CHAR_a, CHAR_i,
    CHAR_a, CHAR_p,
    CHAR_a, CHAR_r,
    CHAR_a, CHAR_s,
    CHAR_a, CHAR_t,
    CHAR_a, CHAR_y,
    CHAR_e, CHAR_a,
    CHAR_e, CHAR_n,
    CHAR_e, CHAR_o,
    CHAR_e, CHAR_r,
    CHAR_h, CHAR_o,
    CHAR_i, CHAR_c,
    CHAR_i, CHAR_e,
    CHAR_i, CHAR_n,
    CHAR_i, CHAR_p,
    CHAR_l, CHAR_a,
    CHAR_l, CHAR_e,
    CHAR_o, CHAR_c,
    CHAR_o, CHAR_i,
    CHAR_o, CHAR_l,
    CHAR_o, CHAR_o,
    CHAR_o, CHAR_p,
    CHAR_o, CHAR_s,
    CHAR_o, CHAR_t,
    CHAR_o, CHAR_u,
    CHAR_o, CHAR_w,
    CHAR_r, CHAR_a,
    CHAR_r, CHAR_e,
    CHAR_r, CHAR_i,
    CHAR_r, CHAR_o,
    CHAR_u, CHAR_b,
    CHAR_u, CHAR_l,
    CHAR_u, CHAR_p,
    CHAR_u, CHAR_r,
    CHAR_u, CHAR_s,
    CHAR_u, CHAR_t,
};

static int q_table[] = {
    CHAR_u, CHAR_a,
    CHAR_u, CHAR_e,
    CHAR_u, CHAR_i,
};

static int r_table[] = {
    CHAR_a, CHAR_c,
    CHAR_a, CHAR_d,
    CHAR_a, CHAR_i,
    CHAR_a, CHAR_n,
    CHAR_a, CHAR_p,
    CHAR_a, CHAR_t,
    CHAR_e, CHAR_a,
    CHAR_e, CHAR_c,
    CHAR_e, CHAR_d,
    CHAR_e, CHAR_f,
    CHAR_e, CHAR_g,
    CHAR_e, CHAR_l,
    CHAR_e, CHAR_m,
    CHAR_e, CHAR_p,
    CHAR_e, CHAR_q,
    CHAR_e, CHAR_s,
    CHAR_e, CHAR_t,
    CHAR_i, CHAR_c,
    CHAR_i, CHAR_d,
    CHAR_i, CHAR_g,
    CHAR_i, CHAR_n,
    CHAR_i, CHAR_s,
    CHAR_i, CHAR_v,
    CHAR_o, CHAR_a,
    CHAR_o, CHAR_c,
    CHAR_o, CHAR_d,
    CHAR_o, CHAR_l,
    CHAR_o, CHAR_o,
    CHAR_o, CHAR_s,
    CHAR_o, CHAR_u,
    CHAR_o, CHAR_w,
    CHAR_u, CHAR_l,
    CHAR_u, CHAR_n,
    CHAR_u, CHAR_s,
};

static int s_table[] = {
    CHAR_a, CHAR_d,
    CHAR_a, CHAR_f,
    CHAR_a, CHAR_i,
    CHAR_a, CHAR_l,
    CHAR_a, CHAR_m,
    CHAR_a, CHAR_n,
    CHAR_a, CHAR_t,
    CHAR_a, CHAR_v,
    CHAR_a, CHAR_w,
    CHAR_a, CHAR_y,
    CHAR_c, CHAR_e,
    CHAR_c, CHAR_h,
    CHAR_c, CHAR_i,
    CHAR_c, CHAR_o,
    CHAR_e, CHAR_a,
    CHAR_e, CHAR_c,
    CHAR_e, CHAR_e,
    CHAR_e, CHAR_l,
    CHAR_e, CHAR_n,
    CHAR_e, CHAR_p,
    CHAR_e, CHAR_r,
    CHAR_e, CHAR_t,
    CHAR_e, CHAR_v,
    CHAR_e, CHAR_x,
    CHAR_h, CHAR_a,
    CHAR_h, CHAR_e,
    CHAR_h, CHAR_i,
    CHAR_h, CHAR_o,
    CHAR_h, CHAR_u,
    CHAR_i, CHAR_c,
    CHAR_i, CHAR_d,
    CHAR_i, CHAR_g,
    CHAR_i, CHAR_l,
    CHAR_i, CHAR_m,
    CHAR_i, CHAR_n,
    CHAR_i, CHAR_s,
    CHAR_i, CHAR_t,
    CHAR_i, CHAR_x,
    CHAR_i, CHAR_z,
    CHAR_k, CHAR_i,
    CHAR_k, CHAR_y,
    CHAR_l, CHAR_e,
    CHAR_l, CHAR_i,
    CHAR_l, CHAR_o,
    CHAR_m, CHAR_a,
    CHAR_m, CHAR_e,
    CHAR_m, CHAR_i,
    CHAR_m, CHAR_o,
    CHAR_n, CHAR_o,
    CHAR_o, CHAR_SPACE,
    CHAR_o, CHAR_a,
    CHAR_o, CHAR_c,
    CHAR_o, CHAR_f,
    CHAR_o, CHAR_i,
    CHAR_o, CHAR_l,
    CHAR_o, CHAR_m,
    CHAR_o, CHAR_n,
    CHAR_o, CHAR_o,
    CHAR_o, CHAR_r,
    CHAR_o, CHAR_u,
    CHAR_p, CHAR_a,
    CHAR_p, CHAR_e,
    CHAR_p, CHAR_i,
    CHAR_p, CHAR_o,
    CHAR_p, CHAR_r,
    CHAR_q, CHAR_u,
    CHAR_t, CHAR_a,
    CHAR_t, CHAR_e,
    CHAR_t, CHAR_i,
    CHAR_t, CHAR_o,
    CHAR_t, CHAR_r,
    CHAR_t, CHAR_u,
    CHAR_t, CHAR_y,
    CHAR_u, CHAR_b,
    CHAR_u, CHAR_c,
    CHAR_u, CHAR_d,
    CHAR_u, CHAR_f,
    CHAR_u, CHAR_g,
    CHAR_u, CHAR_m,
    CHAR_u, CHAR_n,
    CHAR_u, CHAR_p,
    CHAR_u, CHAR_r,
    CHAR_w, CHAR_a,
    CHAR_w, CHAR_e,
    CHAR_w, CHAR_i,
    CHAR_w, CHAR_u,
    CHAR_y, CHAR_s,
};

static int t_table[] = {
    CHAR_a, CHAR_b,
    CHAR_a, CHAR_k,
    CHAR_a, CHAR_l,
    CHAR_a, CHAR_s,
    CHAR_a, CHAR_u,
    CHAR_a, CHAR_x,
    CHAR_e, CHAR_a,
    CHAR_e, CHAR_e,
    CHAR_e, CHAR_l,
    CHAR_e, CHAR_m,
    CHAR_e, CHAR_n,
    CHAR_e, CHAR_r,
    CHAR_e, CHAR_s,
    CHAR_h, CHAR_a,
    CHAR_h, CHAR_e,
    CHAR_h, CHAR_i,
    CHAR_h, CHAR_o,
    CHAR_h, CHAR_r,
    CHAR_h, CHAR_u,
    CHAR_i, CHAR_c,
    CHAR_i, CHAR_e,
    CHAR_i, CHAR_l,
    CHAR_i, CHAR_m,
    CHAR_i, CHAR_r,
    CHAR_i, CHAR_t,
    CHAR_o, CHAR_SPACE,
    CHAR_o, CHAR_d,
    CHAR_o, CHAR_g,
    CHAR_o, CHAR_l,
    CHAR_o, CHAR_m,
    CHAR_o, CHAR_n,
    CHAR_o, CHAR_o,
    CHAR_o, CHAR_p,
    CHAR_o, CHAR_r,
    CHAR_o, CHAR_t,
    CHAR_o, CHAR_u,
    CHAR_o, CHAR_w,
    CHAR_r, CHAR_a,
    CHAR_r, CHAR_e,
    CHAR_r, CHAR_i,
    CHAR_r, CHAR_o,
    CHAR_r, CHAR_u,
    CHAR_r, CHAR_y,
    CHAR_u, CHAR_e,
    CHAR_u, CHAR_r,
    CHAR_v, CHAR_SPACE,
    CHAR_w, CHAR_e,
    CHAR_w, CHAR_i,
    CHAR_w, CHAR_o,
    CHAR_y, CHAR_i,
    CHAR_y, CHAR_p,
};

static int u_table[] = {
    CHAR_n, CHAR_a,
    CHAR_n, CHAR_c,
    CHAR_n, CHAR_d,
    CHAR_n, CHAR_i,
    CHAR_n, CHAR_l,
    CHAR_n, CHAR_t,
    CHAR_p, CHAR_SPACE,
    CHAR_p, CHAR_o,
    CHAR_s, CHAR_SPACE,
    CHAR_s, CHAR_e,
    CHAR_s, CHAR_u,
};

static int v_table[] = {
    CHAR_a, CHAR_l,
    CHAR_a, CHAR_r,
    CHAR_e, CHAR_g,
    CHAR_e, CHAR_r,
    CHAR_i, CHAR_e,
    CHAR_i, CHAR_l,
    CHAR_i, CHAR_s,
    CHAR_o, CHAR_i,
    CHAR_o, CHAR_l,
    CHAR_o, CHAR_t,
};

static int w_table[] = {
    CHAR_a, CHAR_i,
    CHAR_a, CHAR_k,
    CHAR_a, CHAR_l,
    CHAR_a, CHAR_n,
    CHAR_a, CHAR_r,
    CHAR_a, CHAR_s,
    CHAR_a, CHAR_t,
    CHAR_a, CHAR_v,
    CHAR_a, CHAR_y,
    CHAR_e, CHAR_SPACE,
    CHAR_e, CHAR_a,
    CHAR_e, CHAR_d,
    CHAR_e, CHAR_e,
    CHAR_e, CHAR_i,
    CHAR_e, CHAR_l,
    CHAR_e, CHAR_n,
    CHAR_e, CHAR_r,
    CHAR_e, CHAR_s,
    CHAR_e, CHAR_t,
    CHAR_h, CHAR_a,
    CHAR_h, CHAR_e,
    CHAR_h, CHAR_i,
    CHAR_h, CHAR_o,
    CHAR_h, CHAR_y,
    CHAR_i, CHAR_d,
    CHAR_i, CHAR_f,
    CHAR_i, CHAR_l,
    CHAR_i, CHAR_n,
    CHAR_i, CHAR_r,
    CHAR_i, CHAR_s,
    CHAR_i, CHAR_t,
    CHAR_i, CHAR_v,
    CHAR_o, CHAR_k,
    CHAR_o, CHAR_m,
    CHAR_o, CHAR_n,
    CHAR_o, CHAR_o,
    CHAR_o, CHAR_r,
    CHAR_o, CHAR_u,
    CHAR_r, CHAR_i,
    CHAR_r, CHAR_o,
};

static int x_table[] = {
    CHAR_m, CHAR_a,
};

static int y_table[] = {
    CHAR_a, CHAR_r,
    CHAR_e, CHAR_a,
    CHAR_e, CHAR_l,
    CHAR_e, CHAR_n,
    CHAR_e, CHAR_s,
    CHAR_e, CHAR_t,
    CHAR_o, CHAR_u,
};

static int z_table[] = {
    CHAR_e, CHAR_r,
    CHAR_CONTROL_CODE, 0,
};

string_table trigram_table[26] = {
    { CHAR_a, CHAR_A, a_table },
    { CHAR_b, CHAR_B, b_table },
    { CHAR_c, CHAR_C, c_table },
    { CHAR_d, CHAR_D, d_table },
    { CHAR_e, CHAR_E, e_table },
    { CHAR_f, CHAR_F, f_table },
    { CHAR_g, CHAR_G, g_table },
    { CHAR_h, CHAR_H, h_table },
    { CHAR_i, CHAR_I, i_table },
    { CHAR_j, CHAR_J, j_table },
    { CHAR_k, CHAR_K, k_table },
    { CHAR_l, CHAR_L, l_table },
    { CHAR_m, CHAR_M, n_table },
    { CHAR_n, CHAR_N, m_table },
    { CHAR_o, CHAR_O, o_table },
    { CHAR_p, CHAR_P, p_table },
    { CHAR_q, CHAR_Q, q_table },
    { CHAR_r, CHAR_R, r_table },
    { CHAR_s, CHAR_S, s_table },
    { CHAR_t, CHAR_T, t_table },
    { CHAR_u, CHAR_U, u_table },
    { CHAR_v, CHAR_V, v_table },
    { CHAR_w, CHAR_W, w_table },
    { CHAR_x, CHAR_X, x_table },
    { CHAR_y, CHAR_Y, y_table },
    { CHAR_z, CHAR_Z, z_table },
};
